name: mistral
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pytorch=mistral=2.0.0
  - pytorch-cuda=11.8
  - pip:
    - flask
    - flask-restful
    - werkzeug
    - gunicorn
    - transformers
